export PATH=$HOME/.nodebrew/current/bin:$PATH
export PATH=$HOME/.rbenv/bin:$PATH
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
git -C ~/.config commit -a -m"upadte"
git -C ~/.config pull

test -r ~/.bashrc && . ~/.bashrc
