[looper]
manager=["go"]
gorepo="github.com/nathany/looper"

[fzf]
manager=["go"]
gorepo="github.com/junegunn/fzf"

[sacoche]
manager=["go"]
gorepo="github.com/kameike/sacoche"

[dotfiles]
manager=["go"]
gorepo="github.com/rhysd/dotfiles"

[neovim-godev]
manager=["phony"]
dependency=["neovim", "go"]
tasks=["nvim -c GoInstallBinaries -c q"]

[neovim]
manager=["brew"]
dependency=["python-neovim-plugin"]
brewtap="neovim/neovim"

[python-neovim-plugin]
manager=["pip"]
pipname="neovim"

[go]
manager=["brew"]

[nodebrew]
manager=["brew"]

[mas]
manager=["brew"]

[tmp-dir]
manager=["phony"]
checkcommand="ls $HOME/tmp"
tasks=[
  "mkdir -p $HOME/tmp",
]

[node-latest]
manager=["phony"]
dependency=["nodebrew"]
checkcommand="which node"
tasks=[
  "mkdir -p $HOME/.nodebrew",
  "mkdir -p $HOME/.nodebrew/src",
  "nodebrew install-binary latest",
  "nodebrew use latest",
]


[yubico-authenticator]
manager=["phony"]
dependency=["mas"]
tasks=[
  "mas install 1497506650"
]

[git]
manager=["brew"]

[docker]
manager=["brew"]

[tmux]
manager=["brew"]

[openssl]
manager=["brew"]

[readline]
manager=["brew"]


[gh]
brewname="github/gh/gh"
manager=["brew"]

[terraform]
manager=["brew"]


# GUI APPs
[docker-gui]
manager=["brewcask"]
brewname="docker"

[iterm2]
manager=["brewcask"]

[clipy]
manager=["brewcask"]


[google-chrome]
manager=["brewcask"]

[sketch]
manager=["brewcask"]

[slack]
manager=["brewcask"]

[1password]
manager=["brewcask"]

[notion]
manager=["brewcask"]

[macdown]
manager=["brewcask"]

[microsoft-word]
manager=["brewcask"]


[microsoft-powerpoint]
manager=["brewcask"]

[microsoft-excel]
manager=["brewcask"]
