[looper]
manager=["go"]
gorepo="github.com/nathany/looper"

[fzf]
manager=["go"]
gorepo="github.com/junegunn/fzf"

[sacoche]
manager=["go"]
gorepo="github.com/kameike/sacoche"

[dotfiles]
manager=["go"]
gorepo="github.com/rhysd/dotfiles"

[neovim-godev]
manager=["phony"]
dependency=["neovim", "go", "tmp-dir"]
checkcommand="cat $HOME/tmp/.check-neovimgoinstalled"
tasks=[
  "nvim -c GoInstallBinaries -c q",
  "touch $HOME/tmp/.check-neovimgoinstalled",
]

[pod]
manager=["phony"]
dependency=["git"]
checkcommand="which pod"
tasks=[
  "sudo gem install cocoapods",
]

[flutter]
manager=["phony"]
dependency=["git"]
checkcommand="which flutter"
tasks=[
  "git -C ~/.config clone https://github.com/flutter/flutter.git -b stable --depth 1",
]

[flutter-lsp]
manager=["phony"]
dependency=["flutter"]
checkcommand="which dart_language_server"
tasks=[
  "flutter pub global activate dart_language_server",
]

[python]
manager=["brew"]

[python-neovim-plugin]
manager=["phony"]
dependency=["python"]
checkcommand="pip3 show neovim"
task=[
  "pip3 install neovim",
]

[neovim]
manager=["brew"]
dependency=["python-neovim-plugin"]
brewtap="neovim/neovim"

[go]
manager=["brew"]

[imagemagick]
manager=["brew"]

[nodebrew]
manager=["brew"]

[mas]
manager=["brew"]

[tmp-dir]
manager=["phony"]
checkcommand="ls $HOME/tmp"
tasks=[
  "mkdir -p $HOME/tmp",
]

[node-latest]
manager=["phony"]
dependency=["nodebrew"]
checkcommand="which node"
tasks=[
  "mkdir -p $HOME/.nodebrew",
  "mkdir -p $HOME/.nodebrew/src",
  "nodebrew install-binary latest",
  "nodebrew use latest",
]


[mindnode]
manager=["phony"]
dependency=["mas"]
tasks=[
  "mas install 1289197285"
]

[yubico-authenticator]
manager=["phony"]
dependency=["mas"]
tasks=[
  "mas install 1497506650"
]

[git]
manager=["brew"]

[docker]
manager=["brew"]

[tmux]
manager=["brew"]

[openssl]
manager=["brew"]

[readline]
manager=["brew"]

[java]
manager=["brewcask"]

[android-studio]
manager=["brewcask"]
dependency=["java"]




[gh]
brewname="github/gh/gh"
manager=["brew"]

[terraform]
manager=["brew"]


# GUI APPs
[docker-gui]
manager=["brewcask"]
brewname="docker"

[iterm2]
manager=["brewcask"]

[clipy]
manager=["brewcask"]

[google-chrome]
manager=["brewcask"]

[sketch]
manager=["brewcask"]

[slack]
manager=["brewcask"]

[1password]
manager=["brewcask"]

[notion]
manager=["brewcask"]

[macdown]
manager=["brewcask"]

[microsoft-word]
manager=["brewcask"]

[microsoft-powerpoint]
manager=["brewcask"]

[microsoft-excel]
manager=["brewcask"]

[adobe-creative-cloud]
manager=["brewcask"]

# [line]
# manager=["brewcask"]
