export GOPATH=$HOME/go

export PATH=$HOME/.nodebrew/current/bin:$PATH
export PATH=$HOME/.rbenv/bin:$PATH
export PATH=$HOME/Library/Python/3.6/bin/:$PATH
export PATH=$HOME/go/bin/:$PATH

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

alias d-clean='docker rm -v $(docker ps -aq -f status=exited)'
alias sync-config='git -C ~/.config commit -a -m"upadte" &&  git -C ~/.config pull origin master && git -C ~/.config push origin HEAD && source ~/.bashrc'

alias screen-cd-here='pwd | xargs screen -X chdir'
alias sweep-branch='git branch -D `git branch --merged | grep -v \* | xargs`'
alias gohiki='cd ~/gohiki && sh yoshina.sh'

alias move-branch="git branch --move `git branch | grep \* | sed 's/\*//'` "
alias pbedit="pbpaste > ~/tmp/current_buffer && nvim  ~/tmp/current_buffer  && cat ~/tmp/current_buffer | pbcopy"
alias gc="git add --all && git commit"
alias gp="git push `git remote` HEAD"

stty stop undef
stty start undef


