echo "load profile"

# init scripts
test ! -d ~/tmp && mkdir ~/tmp
test ! -d ~/dev && mkdir ~/dev
test ! -d ~/pixiv && mkdir ~/pixiv
test ! -d ~/go && mkdir ~/go

# sync dotfiles
git -C ~/.config commit -a -m"upadte"
git -C ~/.config pull origin master
git -C ~/.config push origin HEAD

# load bashrc
test -r ~/.bashrc && . ~/.bashrc
