echo "load profile"
# load bashrc
test -r ~/.bashrc && . ~/.bashrc


# init scripts
test ! -d "$NIPPO_PATH" && mkdir "$NIPPO_PATH"
test ! -d ~/tmp && mkdir ~/tmp
test ! -d ~/dev && mkdir ~/dev
test ! -d ~/pixiv && mkdir ~/pixiv
test ! -d ~/go && mkdir ~/go

# sync dotfiles
# nohup sync-config > /dev/null & echo "start update config"

screen -r 
