export TMP=$HOME/tmp
export DEV=$HOME/dev
export GOPATH=$HOME/go
export GOROOT=/usr/local/opt/go/libexec/
export CONFIG_PATH=$HOME/.config

export VISUAL=nvim
export EDITOR="$VISUAL"

# js
export PATH=$HOME/.nodebrew/current/bin:$PATH
# ruby
export PATH=$HOME/.rbenv/bin:$PATH
# python
export PATH=$HOME/Library/Python/3.6/bin/:$PATH
# go
export PATH=$GOPATH/bin/:$PATH
export PATH=$GOROOT/bin/:$PATH
# flutter
export PATH=$DEV/flutter/bin:$PATH
# my shell scripts
export PATH=$CONFIG_PATH/bin:$PATH

# markdown stuff
export ICLOUD_PATH=$HOME/Library/Mobile\ Documents
export AUTOMATOR_PATH=$ICLOUD_PATH/com~apple~Automator/Documents
export MARKDOWN_PATH=$ICLOUD_PATH/iCloud~com~coderforart~iOS~MWeb/Documents
export BLOG_PATH=$MARKDOWN_PATH
export NIPPO_PATH=$MARKDOWN_PATH/nippo

# prefix
export PS1="[\W] "


echo "load bashrc"


if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

unalias -a

alias d-clean='docker rm -v $(docker ps -aq -f status=exited)'

alias bashrc='nvim ~/.bashrc && source ~/.bashrc'
alias bash-profile='nvim ~/.bash_profile && source ~/.bash_profile'
alias config='nvim ~/.config'

alias screen-cd-here='pwd | xargs screen -X chdir'
alias sweep-branch='git branch -D `git branch --merged | grep -v \* | xargs`'
alias gohiki='cd ~/gohiki && sh yoshina.sh'
alias go-build-linux='GOOS=linux GOARCH=amd64 go build'


alias move-branch="git branch --move \`git branch | grep \* | sed 's/\*//'\` "
alias pbedit="pbpaste > ~/tmp/current_buffer && nvim  ~/tmp/current_buffer  && cat ~/tmp/current_buffer | pbcopy"
alias pe="pbedit"
alias e="pbedit"
alias gc="git add --all && git commit"
alias gp="git push \`git remote\` HEAD"
alias gf="git fetch"
alias gm="git branch --all | fzf | xargs git merge"
alias gb="git branch --all"
alias gch="git branch --all | fzf | xargs git checkout"
alias gcp="git add --all && git commit &&  git push \`git remote\` HEAD"
alias gs="git status"
alias reload="source ~/.bashrc"
alias c="reload && clear"
alias rand="openssl rand -base64 16 | colrm 17"
alias p="cd ~/pixiv/palcy-ios"
alias pal="cd ~/pixiv/palcy-ios"
alias md="open ~/Library/Mobile\ Documents/iCloud~com~coderforart~iOS~MWeb/Documents/tmp.md"
alias money="open https://docs.google.com/spreadsheets/d/1TE0p2P0aEgg03fYS0aBa5TvXmdZYpAHrDce-LQwJEbo/edit#gid=0"
alias github="open https://github.com/notifications" 
alias editbrewfile="nvim $CONFIG_PATH/brewfile/Brewfile" 
alias close="open '$AUTOMATOR_PATH/killAll.app'" 

alias break="nippo && sleep 300 && say back to work"

stty stop undef
stty start undef

# Copyright (c) 2010, Huy Nguyen, http://www.huyng.com
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without modification, are permitted provided 
# that the following conditions are met:
# 
#     * Redistributions of source code must retain the above copyright notice, this list of conditions 
#       and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
#       following disclaimer in the documentation and/or other materials provided with the distribution.
#     * Neither the name of Huy Nguyen nor the names of contributors
#       may be used to endorse or promote products derived from this software without 
#       specific prior written permission.
#       
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED 
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR 
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
# POSSIBILITY OF SUCH DAMAGE.


# USAGE: 
# s bookmarkname - saves the curr dir as bookmarkname
# g bookmarkname - jumps to the that bookmark
# g b[TAB] - tab completion is available
# p bookmarkname - prints the bookmark
# p b[TAB] - tab completion is available
# d bookmarkname - deletes the bookmark
# d [TAB] - tab completion is available
# l - list all bookmarks

# setup file to store bookmarks
if [ ! -n "$SDIRS" ]; then
    SDIRS=~/.sdirs
fi
touch $SDIRS

RED="0;31m"
GREEN="0;33m"

# save current directory to bookmarks
function s {
    check_help $1
    _bookmark_name_valid "$@"
    if [ -z "$exit_message" ]; then
        _purge_line "$SDIRS" "export DIR_$1="
        CURDIR=$(echo $PWD| sed "s#^$HOME#\$HOME#g")
        echo "export DIR_$1=\"$CURDIR\"" >> $SDIRS
    fi
}

# jump to bookmark
function g {
    check_help $1
    source $SDIRS
    target="$(eval $(echo echo $(echo \$DIR_$1)))"
    if [ -d "$target" ]; then
        cd "$target"
    elif [ ! -n "$target" ]; then
        echo -e "\033[${RED}WARNING: '${1}' bashmark does not exist\033[00m"
    else
        echo -e "\033[${RED}WARNING: '${target}' does not exist\033[00m"
    fi
}

# print bookmark
function p {
    check_help $1
    source $SDIRS
    echo "$(eval $(echo echo $(echo \$DIR_$1)))"
}

# delete bookmark
function d {
    check_help $1
    _bookmark_name_valid "$@"
    if [ -z "$exit_message" ]; then
        _purge_line "$SDIRS" "export DIR_$1="
        unset "DIR_$1"
    fi
}

# print out help for the forgetful
function check_help {
    if [ "$1" = "-h" ] || [ "$1" = "-help" ] || [ "$1" = "--help" ] ; then
        echo ''
        echo 's <bookmark_name> - Saves the current directory as "bookmark_name"'
        echo 'g <bookmark_name> - Goes (cd) to the directory associated with "bookmark_name"'
        echo 'p <bookmark_name> - Prints the directory associated with "bookmark_name"'
        echo 'd <bookmark_name> - Deletes the bookmark'
        echo 'l                 - Lists all available bookmarks'
        kill -SIGINT $$
    fi
}

# list bookmarks with dirnam
function l {
    check_help $1
    source $SDIRS
        
    # if color output is not working for you, comment out the line below '\033[1;32m' == "red"
    env | sort | awk '/^DIR_.+/{split(substr($0,5),parts,"="); printf("\033[0;33m%-20s\033[0m %s\n", parts[1], parts[2]);}'
    
    # uncomment this line if color output is not working with the line above
    # env | grep "^DIR_" | cut -c5- | sort |grep "^.*=" 
}
# list bookmarks without dirname
function _l {
    source $SDIRS
    env | grep "^DIR_" | cut -c5- | sort | grep "^.*=" | cut -f1 -d "=" 
}

# validate bookmark name
function _bookmark_name_valid {
    exit_message=""
    if [ -z $1 ]; then
        exit_message="bookmark name required"
        echo $exit_message
    elif [ "$1" != "$(echo $1 | sed 's/[^A-Za-z0-9_]//g')" ]; then
        exit_message="bookmark name is not valid"
        echo $exit_message
    fi
}

# completion command
function _comp {
    local curw
    COMPREPLY=()
    curw=${COMP_WORDS[COMP_CWORD]}
    COMPREPLY=($(compgen -W '`_l`' -- $curw))
    return 0
}

# ZSH completion command
function _compzsh {
    reply=($(_l))
}

# safe delete line from sdirs
function _purge_line {
    if [ -s "$1" ]; then
        # safely create a temp file
        t=$(mktemp -t bashmarks.XXXXXX) || exit 1
        trap "/bin/rm -f -- '$t'" EXIT

        # purge line
        sed "/$2/d" "$1" > "$t"
        /bin/mv "$t" "$1"

        # cleanup temp file
        /bin/rm -f -- "$t"
        trap - EXIT
    fi
}

# bind completion command for g,p,d to _comp
if [ $ZSH_VERSION ]; then
    compctl -K _compzsh g
    compctl -K _compzsh p
    compctl -K _compzsh d
else
    shopt -s progcomp
    complete -F _comp g
    complete -F _comp p
    complete -F _comp d
fi
