# vim: syntax=sh
# lang
brew elm
brew python
brew erlang
brew go
brew dep
brew rbenv
brew ruby-build
brew node
brew nodebrew

#utils
brew git
brew docker

#ios
brew carthage
brew cocoapods

# Other Homebrew packages
brew aws-elasticbeanstalk
brew brew-file
brew ffmpeg
brew fzf
brew gd
brew gdbm
brew gettext
brew ghostscript
brew ios-deploy
brew kubernetes-cli
brew neovim
brew openssl
brew pv
brew python@2
brew screen
brew swiftlint

# Other Cask applications
cask docker
cask macdown
cask minikube
cask virtualbox
cask visutal-studio-code

# App Store applications
appstore 1142151959 JustFocus (1.6.1)
appstore 409183694 Keynote (8.1)
appstore 1289197285 MindNode (5.1.3)
appstore 409203825 Numbers (5.1)
appstore 409201541 Pages (7.1)
appstore 497799835 Xcode (9.4.1)
