# vim: syntax=sh

# taps
tap dart-lang/dart
tap heroku/brew
tap neovim/neovim
tap argon/mas

# lang
brew elm
brew python
brew erlang
brew go
brew dep
brew rbenv
brew ruby-build
brew node
brew yarn
brew nodebrew
brew dart

#utils
brew git
brew docker
brew imagemagick
# brew conan

#ios
brew carthage
brew cocoapods

#flutter
brew --HEAD libimobiledevice
brew ideviceinstaller

# Other Homebrew packages
brew aws-elasticbeanstalk
brew brew-file
brew ffmpeg
brew fzf
brew gd
brew gdbm
brew gettext
brew ghostscript
brew ios-deploy
brew kubernetes-cli
brew neovim
brew openssl
brew pv
brew screen
brew mas


# Other Cask applications
cask docker
cask iterm2
cask macdown
cask minikube
cask virtualbox
cask visual-studio-code
cask charles
cask slack
cask notion

# App Store applications
appstore 1142151959 JustFocus (1.6.1)
appstore 409183694 Keynote (8.1)
appstore 1289197285 MindNode (5.1.3)
appstore 409203825 Numbers (5.1)
appstore 409201541 Pages (7.1)
appstore 497799835 Xcode (9.4.1)
# brew swiftlint
